from __future__ import annotations

import csv
import html
import json
from pathlib import Path

import openpyxl


ROOT = Path(__file__).resolve().parents[3]
OUT_DIR = ROOT / "docs" / "design" / "data-model" / "physical-schema"
DBMODEL = ROOT / "docs" / "design" / "data-model" / "source" / "dbmodel.xlsx"


SOURCES = [
    {
        "label": "Microsoft Learn: Configure table relationship cascading behavior",
        "url": "https://learn.microsoft.com/en-us/power-apps/developer/data-platform/configure-entity-relationship-cascading-behavior",
        "use": "Restrict delete and no-cascade relationship policy.",
    },
    {
        "label": "Microsoft Learn: Work with alternate keys",
        "url": "https://learn.microsoft.com/en-us/power-apps/developer/data-platform/define-alternate-keys-entity",
        "use": "Alternate key limits and field eligibility.",
    },
    {
        "label": "Microsoft Learn: Manage Dataverse auditing",
        "url": "https://learn.microsoft.com/en-us/power-platform/admin/manage-dataverse-auditing",
        "use": "Environment, table, and column audit enablement.",
    },
    {
        "label": "Microsoft Learn: Set up bookable resources",
        "url": "https://learn.microsoft.com/en-us/dynamics365/field-service/set-up-bookable-resources",
        "use": "Field Service resource types, characteristics, categories, territories, work hours, and availability alignment.",
    },
]


def field(logical, display, dtype, required, constraints, purpose, security="Standard"):
    return {
        "logical": logical,
        "display": display,
        "type": dtype,
        "required": required,
        "constraints": constraints,
        "purpose": purpose,
        "security": security,
    }


def rel(name, lookup, target, required, purpose, cascade="Delete Restrict; assign/share/reparent No Cascade"):
    return {
        "relationship": name,
        "lookup": lookup,
        "target": target,
        "cardinality": "N:1 from proposed table to target; 1:N from target to proposed table",
        "required": required,
        "cascade": cascade,
        "purpose": purpose,
    }


ENTITIES = [
    {
        "logical": "ccsb_resourcecapability",
        "display": "Resource Capability",
        "plural": "Resource Capabilities",
        "ownership": "UserOwned",
        "audit": "Enable table and column audit for all business fields.",
        "solution": "CCSB Foundation Schema v1.1 proposed",
        "purpose": "Normalized resource skill, certification, clearance, category, territory, facility feature, or capacity capability used by eligibility and requirement rules.",
        "alignment": "Maps to Field Service bookable resource characteristics, resource categories, territories, and proficiency/rating concepts while remaining product-owned and optional when Field Service is not installed.",
        "alternate_keys": ["ccsb_ResourceCapability_Key: ccsb_capabilitykey"],
        "fields": [
            field("ccsb_resourcecapabilityid", "Resource Capability", "Uniqueidentifier", "System", "Primary ID; generated by Dataverse.", "Unique row identifier."),
            field("ccsb_name", "Resource Capability Name", "Primary Name", "Yes", "Max 300.", "Human-readable capability label."),
            field("ccsb_capabilitykey", "Capability Key", "Text", "Yes", "Max 200; alternate key; sanitized for Dataverse upsert.", "Stable capability identity within CCSB."),
            field("ccsb_resourceid", "Resource", "Lookup", "Runtime required", "Target ccsb_resource; metadata optional for migration safety.", "Resource holding the capability."),
            field("ccsb_boardversionid", "Board Version", "Lookup", "No", "Target ccsb_boardversion.", "Configuration version that governs this capability mapping."),
            field("ccsb_resourceroleid", "Resource Role", "Lookup", "No", "Target ccsb_resourcerole.", "Role that this capability satisfies or qualifies."),
            field("ccsb_capabilitytype", "Capability Type", "Choice", "Yes", "Skill, Certification, License, Clearance, Equipment Feature, Facility Feature, Territory, Category, Other.", "Classifies the capability."),
            field("ccsb_capabilitysource", "Capability Source", "Choice", "Yes", "Native CCSB, Field Service, Project Operations, Customer Source, External.", "Records the source system or mapping origin."),
            field("ccsb_externalkey", "External Key", "Text", "No", "Max 200.", "Stable source-system key when synchronized."),
            field("ccsb_sourcetablelogicalname", "Source Table Logical Name", "Text", "No", "Max 128.", "Logical name of the originating Dataverse table, such as bookableresourcecharacteristic."),
            field("ccsb_sourcerecordid", "Source Record ID", "Text", "No", "Max 100; GUID string when Dataverse sourced.", "Source record identifier without hard dependency on optional Field Service tables."),
            field("ccsb_proficiencymodel", "Proficiency Model", "Text", "No", "Max 100.", "Name/code of the rating model used by the source."),
            field("ccsb_proficiencyvalue", "Proficiency Value", "Decimal", "No", "Precision 2.", "Comparable numeric capability score."),
            field("ccsb_proficiencylabel", "Proficiency Label", "Text", "No", "Max 100.", "Display label for proficiency or certification level."),
            field("ccsb_capacityunits", "Capacity Units", "Decimal", "No", "Precision 2.", "Capability-specific capacity contribution where applicable."),
            field("ccsb_effectivefrom", "Effective From", "Date and Time", "No", "User local; stored UTC.", "Start of capability validity."),
            field("ccsb_effectiveto", "Effective To", "Date and Time", "No", "User local; stored UTC.", "End of capability validity."),
            field("ccsb_verificationstatus", "Verification Status", "Choice", "Yes", "Not Verified, Verified, Expired, Revoked, Not Required.", "Controls whether the capability may satisfy strict requirements."),
            field("ccsb_verifiedon", "Verified On", "Date and Time", "No", "User local; stored UTC.", "Timestamp of verification."),
            field("ccsb_verifiedby", "Verified By", "Lookup", "No", "Target systemuser.", "User who verified the capability."),
            field("ccsb_isactive", "Active", "Boolean", "Yes", "Default Yes.", "Excludes inactive capabilities from eligibility."),
            field("ccsb_sourcehash", "Source Hash", "Text", "No", "Max 128.", "Detects source drift without storing full source payload."),
            field("ccsb_notes", "Notes", "Multiline Text", "No", "Max 100000; field security recommended.", "Restricted notes; do not store medical/private details unless approved.", "Field Security"),
        ],
        "relationships": [
            rel("ccsb_resource_ccsb_resourcecapability", "ccsb_resourceid", "ccsb_resource", "Runtime required", "One resource has many capabilities."),
            rel("ccsb_boardversion_ccsb_resourcecapability", "ccsb_boardversionid", "ccsb_boardversion", "Optional", "Capabilities may be version-scoped."),
            rel("ccsb_resourcerole_ccsb_resourcecapability", "ccsb_resourceroleid", "ccsb_resourcerole", "Optional", "Capability may qualify a resource for a configured role."),
            rel("systemuser_ccsb_resourcecapability_verifiedby", "ccsb_verifiedby", "systemuser", "Optional", "Tracks verifier without changing owner."),
        ],
    },
    {
        "logical": "ccsb_operationaudit",
        "display": "Operation Audit",
        "plural": "Operation Audits",
        "ownership": "UserOwned",
        "audit": "Enable Dataverse audit and also enforce append-only CCSB audit semantics.",
        "solution": "CCSB Foundation Schema v1.1 proposed",
        "purpose": "Append-only product audit evidence for commands, validations, security decisions, confirmations, publishes, rollbacks, support reads, and integration transitions.",
        "alignment": "Complements Dataverse auditing and plug-in trace data with product-scoped operation, reason, policy, correlation, and before/after evidence.",
        "alternate_keys": ["ccsb_OperationAudit_Key: ccsb_auditkey"],
        "fields": [
            field("ccsb_operationauditid", "Operation Audit", "Uniqueidentifier", "System", "Primary ID; generated by Dataverse.", "Unique row identifier."),
            field("ccsb_name", "Operation Audit Name", "Primary Name", "Yes", "Max 300.", "Readable audit event title."),
            field("ccsb_auditkey", "Audit Key", "Text", "Yes", "Max 200; alternate key.", "Stable event key for support lookup and idempotent writes."),
            field("ccsb_operationid", "Operation", "Lookup", "Runtime required", "Target ccsb_operation; metadata optional.", "Parent operation producing the event."),
            field("ccsb_operationitemid", "Operation Item", "Lookup", "No", "Target ccsb_operationitem.", "Optional child operation item."),
            field("ccsb_boardid", "Board", "Lookup", "No", "Target ccsb_board.", "Board scope for security and support filters."),
            field("ccsb_boardversionid", "Board Version", "Lookup", "No", "Target ccsb_boardversion.", "Configuration version in effect."),
            field("ccsb_scheduleversionid", "Schedule Version", "Lookup", "No", "Target ccsb_scheduleversion.", "Operational schedule version in effect."),
            field("ccsb_schedulechangeid", "Schedule Change", "Lookup", "No", "Target ccsb_schedulechange.", "Change ledger record linked to this event."),
            field("ccsb_publishsnapshotid", "Publish Snapshot", "Lookup", "No", "Target ccsb_publishsnapshot.", "Publish evidence linked to this event."),
            field("ccsb_publishsnapshotitemid", "Publish Snapshot Item", "Lookup", "No", "Target ccsb_publishsnapshotitem.", "Snapshot item linked to this event."),
            field("ccsb_publishlockid", "Publish Lock", "Lookup", "No", "Target ccsb_publishlock.", "Lock linked to this event."),
            field("ccsb_conflictid", "Conflict", "Lookup", "No", "Target ccsb_conflict.", "Conflict or warning linked to this event."),
            field("ccsb_actorid", "Actor", "Lookup", "No", "Target systemuser.", "Dataverse user executing or causing the event."),
            field("ccsb_actorprincipaltype", "Actor Principal Type", "Choice", "Yes", "System User, Team, Application User, System Process, External Principal.", "Classifies the actor."),
            field("ccsb_actorprincipalid", "Actor Principal ID", "Text", "No", "Max 100.", "Dataverse or Entra principal identifier."),
            field("ccsb_actordisplayname", "Actor Display Name", "Text", "No", "Max 300; field security recommended.", "Friendly actor name captured for support.", "Field Security"),
            field("ccsb_auditeventtype", "Audit Event Type", "Choice", "Yes", "Command Requested, Validation Result, Security Decision, Warning Confirmed, Change Committed, Publish Committed, Rollback Committed, Failure, Support Read.", "High-level event category."),
            field("ccsb_actiontype", "Action Type", "Choice", "Yes", "Validate, Execute, Publish, Rollback, Lock, Unlock, Override, Activate, Generate Projection, Integration.", "Product action attempted."),
            field("ccsb_outcome", "Outcome", "Choice", "Yes", "Started, Succeeded, Warning, Blocked, Failed, Denied, Cancelled.", "Result of the event."),
            field("ccsb_severity", "Severity", "Choice", "Yes", "Information, Warning, Error, Critical, Security.", "Support triage severity."),
            field("ccsb_correlationid", "Correlation ID", "Text", "Yes", "Max 100; same value as operation correlation where available.", "End-to-end trace correlation."),
            field("ccsb_causationid", "Causation ID", "Text", "No", "Max 100.", "Links event to the event/request that caused it."),
            field("ccsb_idempotencykey", "Idempotency Key", "Text", "No", "Max 200.", "Duplicate detection key for command requests."),
            field("ccsb_clientrequestid", "Client Request ID", "Text", "No", "Max 100.", "Client-provided request identifier."),
            field("ccsb_uirequestid", "UI Request ID", "Text", "No", "Max 100.", "PCF/session request identifier for support."),
            field("ccsb_targetscopetype", "Target Scope Type", "Choice", "No", "Board, Board Version, Schedule Version, Date Range, Resource, Group, Record, Operation.", "Scope type affected."),
            field("ccsb_sourceentitylogicalname", "Source Entity Logical Name", "Text", "No", "Max 128.", "Source table logical name when event concerns a mapped/customer record."),
            field("ccsb_sourcerecordid", "Source Record ID", "Text", "No", "Max 100.", "Source record identifier."),
            field("ccsb_targetentitylogicalname", "Target Entity Logical Name", "Text", "No", "Max 128.", "Target table logical name when different from source."),
            field("ccsb_targetrecordid", "Target Record ID", "Text", "No", "Max 100.", "Target record identifier."),
            field("ccsb_reasoncategory", "Reason Category", "Choice", "No", "User Reason, Policy Override, Conflict Override, System Recovery, Support Action, Migration.", "Reason classification."),
            field("ccsb_reasontext", "Reason Text", "Multiline Text", "No", "Max 4000; field security recommended.", "User/system rationale.", "Field Security"),
            field("ccsb_beforeimagejson", "Before Image JSON", "Multiline Text", "No", "Max 100000; field security recommended.", "Minimal before-image for managed fields.", "Field Security"),
            field("ccsb_afterimagejson", "After Image JSON", "Multiline Text", "No", "Max 100000; field security recommended.", "Minimal after-image for managed fields.", "Field Security"),
            field("ccsb_deltajson", "Delta JSON", "Multiline Text", "No", "Max 100000; field security recommended.", "Normalized changed field/value summary.", "Field Security"),
            field("ccsb_diagnosticjson", "Diagnostic JSON", "Multiline Text", "No", "Max 100000; field security recommended.", "Safe machine diagnostics; avoid secrets and raw PII.", "Field Security"),
            field("ccsb_policyversion", "Policy Version", "Text", "No", "Max 50.", "Authorization/rule policy version evaluated."),
            field("ccsb_occurredon", "Occurred On", "Date and Time", "Yes", "User local; stored UTC.", "Event timestamp."),
            field("ccsb_retentionuntil", "Retention Until", "Date and Time", "No", "User local; stored UTC.", "Earliest archive/purge eligibility."),
            field("ccsb_evidencehash", "Evidence Hash", "Text", "No", "Max 128.", "Hash of normalized evidence JSON."),
            field("ccsb_previousevidencehash", "Previous Evidence Hash", "Text", "No", "Max 128.", "Optional hash-chain pointer."),
            field("ccsb_isimmutable", "Immutable", "Boolean", "Yes", "Default Yes.", "Server-side update/delete guard."),
        ],
        "relationships": [
            rel("ccsb_operation_ccsb_operationaudit", "ccsb_operationid", "ccsb_operation", "Runtime required", "Operation has many audit events."),
            rel("ccsb_operationitem_ccsb_operationaudit", "ccsb_operationitemid", "ccsb_operationitem", "Optional", "Operation item may have audit details."),
            rel("ccsb_board_ccsb_operationaudit", "ccsb_boardid", "ccsb_board", "Optional", "Board-scoped support filtering."),
            rel("ccsb_boardversion_ccsb_operationaudit", "ccsb_boardversionid", "ccsb_boardversion", "Optional", "Configuration version linkage."),
            rel("ccsb_scheduleversion_ccsb_operationaudit", "ccsb_scheduleversionid", "ccsb_scheduleversion", "Optional", "Schedule version linkage."),
            rel("ccsb_schedulechange_ccsb_operationaudit", "ccsb_schedulechangeid", "ccsb_schedulechange", "Optional", "Change ledger audit linkage."),
            rel("ccsb_publishsnapshot_ccsb_operationaudit", "ccsb_publishsnapshotid", "ccsb_publishsnapshot", "Optional", "Publish snapshot audit linkage."),
            rel("ccsb_publishsnapshotitem_ccsb_operationaudit", "ccsb_publishsnapshotitemid", "ccsb_publishsnapshotitem", "Optional", "Snapshot item audit linkage."),
            rel("ccsb_publishlock_ccsb_operationaudit", "ccsb_publishlockid", "ccsb_publishlock", "Optional", "Lock audit linkage."),
            rel("ccsb_conflict_ccsb_operationaudit", "ccsb_conflictid", "ccsb_conflict", "Optional", "Conflict audit linkage."),
            rel("systemuser_ccsb_operationaudit_actor", "ccsb_actorid", "systemuser", "Optional", "Actor lookup for Dataverse users."),
        ],
    },
    {
        "logical": "ccsb_schedulechange",
        "display": "Schedule Change",
        "plural": "Schedule Changes",
        "ownership": "UserOwned",
        "audit": "Enable table and column audit; enforce append-only or state-forward-only transitions.",
        "solution": "CCSB Foundation Schema v1.1 proposed",
        "purpose": "Controlled ledger of proposed, committed, published, superseded, or rolled-back schedule mutations.",
        "alignment": "Maps to changes that would otherwise be made directly to bookings, assignments, or requirements in Field Service/Project Operations. CCSB keeps the ledger product-owned so all mutations flow through Custom APIs.",
        "alternate_keys": ["ccsb_ScheduleChange_Key: ccsb_changekey"],
        "fields": [
            field("ccsb_schedulechangeid", "Schedule Change", "Uniqueidentifier", "System", "Primary ID; generated by Dataverse.", "Unique row identifier."),
            field("ccsb_name", "Schedule Change Name", "Primary Name", "Yes", "Max 300.", "Readable change label."),
            field("ccsb_changekey", "Change Key", "Text", "Yes", "Max 200; alternate key.", "Stable identity for one logical schedule mutation."),
            field("ccsb_boardid", "Board", "Lookup", "Runtime required", "Target ccsb_board; metadata optional.", "Board scope."),
            field("ccsb_boardversionid", "Board Version", "Lookup", "Runtime required", "Target ccsb_boardversion; metadata optional.", "Configuration version used to interpret mappings."),
            field("ccsb_scheduleversionid", "Schedule Version", "Lookup", "No", "Target ccsb_scheduleversion.", "Operational schedule version."),
            field("ccsb_scheduleitemid", "Schedule Item", "Lookup", "No", "Target ccsb_scheduleitem.", "Affected activity/booking/service item."),
            field("ccsb_scheduleassignmentid", "Schedule Assignment", "Lookup", "No", "Target ccsb_scheduleassignment.", "Affected assignment."),
            field("ccsb_schedulerequirementid", "Schedule Requirement", "Lookup", "No", "Target ccsb_schedulerequirement.", "Affected requirement."),
            field("ccsb_resourceid", "Resource", "Lookup", "No", "Target ccsb_resource.", "Affected resource."),
            field("ccsb_operationid", "Operation", "Lookup", "Runtime required", "Target ccsb_operation; metadata optional.", "Operation that created or committed the change."),
            field("ccsb_operationitemid", "Operation Item", "Lookup", "No", "Target ccsb_operationitem.", "Operation item for this record."),
            field("ccsb_publishsnapshotid", "Publish Snapshot", "Lookup", "No", "Target ccsb_publishsnapshot.", "Snapshot that includes this change."),
            field("ccsb_publishsnapshotitemid", "Publish Snapshot Item", "Lookup", "No", "Target ccsb_publishsnapshotitem.", "Snapshot item evidence."),
            field("ccsb_publishlockid", "Publish Lock", "Lookup", "No", "Target ccsb_publishlock.", "Lock that blocked or protected the change."),
            field("ccsb_conflictid", "Conflict", "Lookup", "No", "Target ccsb_conflict.", "Conflict produced by this change."),
            field("ccsb_correlationid", "Correlation ID", "Text", "Yes", "Max 100.", "Trace correlation shared across operation/audit records."),
            field("ccsb_changetype", "Change Type", "Choice", "Yes", "Create, Update, Move, Resize, Assign, Unassign, Reassign, Status Change, Requirement Change, Publish, Rollback.", "Business mutation category."),
            field("ccsb_changestate", "Change State", "Choice", "Yes", "Draft, Pending Validation, Pending Approval, Approved, Committed, Pending Publish, Published, Superseded, Rolled Back, Rejected, Cancelled.", "Lifecycle of the change."),
            field("ccsb_sourceorigin", "Source Origin", "Choice", "Yes", "Native CCSB, Customer Mapped, Field Service, Project Operations, Import, System.", "Origin of the affected schedule data."),
            field("ccsb_sourceentitylogicalname", "Source Entity Logical Name", "Text", "No", "Max 128.", "Mapped source table logical name."),
            field("ccsb_sourcerecordid", "Source Record ID", "Text", "No", "Max 100.", "Mapped source record identifier."),
            field("ccsb_sourcerowversion", "Source Row Version", "Text", "No", "Max 100.", "Concurrency token from source record."),
            field("ccsb_targetentitylogicalname", "Target Entity Logical Name", "Text", "No", "Max 128.", "Target table for writes where different from source."),
            field("ccsb_targetrecordid", "Target Record ID", "Text", "No", "Max 100.", "Target record identifier."),
            field("ccsb_fieldscopejson", "Field Scope JSON", "Multiline Text", "Yes", "Max 100000.", "Approved field list governed by active mapping policy."),
            field("ccsb_beforeimagejson", "Before Image JSON", "Multiline Text", "No", "Max 100000; field security recommended.", "Managed before-image.", "Field Security"),
            field("ccsb_proposedimagejson", "Proposed Image JSON", "Multiline Text", "No", "Max 100000; field security recommended.", "Proposed values before commit.", "Field Security"),
            field("ccsb_committedimagejson", "Committed Image JSON", "Multiline Text", "No", "Max 100000; field security recommended.", "Values written or accepted.", "Field Security"),
            field("ccsb_rollbackimagejson", "Rollback Image JSON", "Multiline Text", "No", "Max 100000; field security recommended.", "Rollback candidate image for managed fields only.", "Field Security"),
            field("ccsb_ruleoutcomejson", "Rule Outcome JSON", "Multiline Text", "No", "Max 100000.", "Rule, warning, and blocker summary."),
            field("ccsb_requiresapproval", "Requires Approval", "Boolean", "Yes", "Default No.", "Indicates approval is required before commit/publish."),
            field("ccsb_approvedby", "Approved By", "Lookup", "No", "Target systemuser.", "Approver when required."),
            field("ccsb_approvedon", "Approved On", "Date and Time", "No", "User local; stored UTC.", "Approval timestamp."),
            field("ccsb_overridereason", "Override Reason", "Multiline Text", "No", "Max 4000; field security recommended.", "Required reason for overrides.", "Field Security"),
            field("ccsb_requestedby", "Requested By", "Lookup", "No", "Target systemuser.", "User who requested the change."),
            field("ccsb_requestedon", "Requested On", "Date and Time", "Yes", "User local; stored UTC.", "Request timestamp."),
            field("ccsb_committedon", "Committed On", "Date and Time", "No", "User local; stored UTC.", "Commit timestamp."),
            field("ccsb_publishedon", "Published On", "Date and Time", "No", "User local; stored UTC.", "Publish timestamp."),
            field("ccsb_retentionuntil", "Retention Until", "Date and Time", "No", "User local; stored UTC.", "Earliest archive/purge eligibility."),
            field("ccsb_changehash", "Change Hash", "Text", "No", "Max 128.", "Hash of normalized change evidence."),
            field("ccsb_isrollbackcandidate", "Rollback Candidate", "Boolean", "Yes", "Default Yes for managed-field changes.", "Eligible for rollback snapshot inclusion."),
        ],
        "relationships": [
            rel("ccsb_board_ccsb_schedulechange", "ccsb_boardid", "ccsb_board", "Runtime required", "Board owns many schedule changes."),
            rel("ccsb_boardversion_ccsb_schedulechange", "ccsb_boardversionid", "ccsb_boardversion", "Runtime required", "Configuration context for change evaluation."),
            rel("ccsb_scheduleversion_ccsb_schedulechange", "ccsb_scheduleversionid", "ccsb_scheduleversion", "Optional", "Operational schedule version."),
            rel("ccsb_scheduleitem_ccsb_schedulechange", "ccsb_scheduleitemid", "ccsb_scheduleitem", "Optional", "Affected schedule item."),
            rel("ccsb_scheduleassignment_ccsb_schedulechange", "ccsb_scheduleassignmentid", "ccsb_scheduleassignment", "Optional", "Affected assignment."),
            rel("ccsb_schedulerequirement_ccsb_schedulechange", "ccsb_schedulerequirementid", "ccsb_schedulerequirement", "Optional", "Affected requirement."),
            rel("ccsb_resource_ccsb_schedulechange", "ccsb_resourceid", "ccsb_resource", "Optional", "Affected resource."),
            rel("ccsb_operation_ccsb_schedulechange", "ccsb_operationid", "ccsb_operation", "Runtime required", "Operation that created/committed the change."),
            rel("ccsb_operationitem_ccsb_schedulechange", "ccsb_operationitemid", "ccsb_operationitem", "Optional", "Operation item linked to the change."),
            rel("ccsb_publishsnapshot_ccsb_schedulechange", "ccsb_publishsnapshotid", "ccsb_publishsnapshot", "Optional", "Snapshot including the change."),
            rel("ccsb_publishsnapshotitem_ccsb_schedulechange", "ccsb_publishsnapshotitemid", "ccsb_publishsnapshotitem", "Optional", "Snapshot item for this change."),
            rel("ccsb_publishlock_ccsb_schedulechange", "ccsb_publishlockid", "ccsb_publishlock", "Optional", "Lock that affected the change."),
            rel("ccsb_conflict_ccsb_schedulechange", "ccsb_conflictid", "ccsb_conflict", "Optional", "Conflict caused/resolved by this change."),
            rel("systemuser_ccsb_schedulechange_requestedby", "ccsb_requestedby", "systemuser", "Optional", "Requester lookup."),
            rel("systemuser_ccsb_schedulechange_approvedby", "ccsb_approvedby", "systemuser", "Optional", "Approver lookup."),
        ],
    },
    {
        "logical": "ccsb_publishsnapshotitem",
        "display": "Publish Snapshot Item",
        "plural": "Publish Snapshot Items",
        "ownership": "OrganizationOwned",
        "audit": "Enable audit; update/delete denied except system archive process.",
        "solution": "CCSB Foundation Schema v1.1 proposed",
        "purpose": "Immutable item-level evidence for every record/field included in a publish or rollback snapshot.",
        "alignment": "Complements ccsb_publishsnapshot header and avoids storing all official-state evidence only in a large JSON manifest. No direct Field Service table equivalent.",
        "alternate_keys": ["ccsb_PublishSnapshotItem_Key: ccsb_snapshotitemkey"],
        "fields": [
            field("ccsb_publishsnapshotitemid", "Publish Snapshot Item", "Uniqueidentifier", "System", "Primary ID; generated by Dataverse.", "Unique row identifier."),
            field("ccsb_name", "Publish Snapshot Item Name", "Primary Name", "Yes", "Max 300.", "Readable snapshot item name."),
            field("ccsb_snapshotitemkey", "Snapshot Item Key", "Text", "Yes", "Max 200; alternate key.", "Stable snapshot item identity."),
            field("ccsb_publishsnapshotid", "Publish Snapshot", "Lookup", "Runtime required", "Target ccsb_publishsnapshot; metadata optional.", "Parent snapshot header."),
            field("ccsb_boardid", "Board", "Lookup", "No", "Target ccsb_board.", "Board scope."),
            field("ccsb_boardversionid", "Board Version", "Lookup", "No", "Target ccsb_boardversion.", "Configuration version scope."),
            field("ccsb_scheduleversionid", "Schedule Version", "Lookup", "No", "Target ccsb_scheduleversion.", "Schedule version scope."),
            field("ccsb_operationid", "Operation", "Lookup", "No", "Target ccsb_operation.", "Publish/rollback operation."),
            field("ccsb_operationitemid", "Operation Item", "Lookup", "No", "Target ccsb_operationitem.", "Operation item that produced this row."),
            field("ccsb_schedulechangeid", "Schedule Change", "Lookup", "No", "Target ccsb_schedulechange.", "Change captured by this item."),
            field("ccsb_scheduleitemid", "Schedule Item", "Lookup", "No", "Target ccsb_scheduleitem.", "Native schedule item if applicable."),
            field("ccsb_scheduleassignmentid", "Schedule Assignment", "Lookup", "No", "Target ccsb_scheduleassignment.", "Native assignment if applicable."),
            field("ccsb_schedulerequirementid", "Schedule Requirement", "Lookup", "No", "Target ccsb_schedulerequirement.", "Native requirement if applicable."),
            field("ccsb_resourceid", "Resource", "Lookup", "No", "Target ccsb_resource.", "Resource associated with this item."),
            field("ccsb_sequencenumber", "Sequence Number", "Whole Number", "Yes", "Starts at 1 within snapshot.", "Deterministic order for replay/diff."),
            field("ccsb_itemtype", "Item Type", "Choice", "Yes", "Schedule Item, Assignment, Requirement, Resource, Lock, Change, Conflict, Rollback Image, External Source Record.", "Type of captured item."),
            field("ccsb_itemstatus", "Item Status", "Choice", "Yes", "Captured, Published, Superseded, Rolled Back, Excluded, Error.", "Lifecycle/status of the snapshot item."),
            field("ccsb_sourceentitylogicalname", "Source Entity Logical Name", "Text", "No", "Max 128.", "Mapped/customer source table."),
            field("ccsb_sourcerecordid", "Source Record ID", "Text", "No", "Max 100.", "Mapped/customer source record."),
            field("ccsb_sourcerowversion", "Source Row Version", "Text", "No", "Max 100.", "Source concurrency token at capture time."),
            field("ccsb_sourceversionnumber", "Source Version Number", "Text", "No", "Max 100.", "Dataverse or external version marker."),
            field("ccsb_managedfieldscopejson", "Managed Field Scope JSON", "Multiline Text", "Yes", "Max 100000.", "Exact rollback-managed fields captured."),
            field("ccsb_beforeimagejson", "Before Image JSON", "Multiline Text", "No", "Max 100000; field security recommended.", "Managed before-image.", "Field Security"),
            field("ccsb_afterimagejson", "After Image JSON", "Multiline Text", "No", "Max 100000; field security recommended.", "Managed after-image/official image.", "Field Security"),
            field("ccsb_rollbackimagejson", "Rollback Image JSON", "Multiline Text", "No", "Max 100000; field security recommended.", "Image used for field-scoped rollback.", "Field Security"),
            field("ccsb_relationshipcontextjson", "Relationship Context JSON", "Multiline Text", "No", "Max 100000.", "Parent/sibling/group/resource context needed for support and rollback checks."),
            field("ccsb_itemhash", "Item Hash", "Text", "No", "Max 128.", "Hash of normalized item evidence."),
            field("ccsb_previousitemhash", "Previous Item Hash", "Text", "No", "Max 128.", "Hash-chain support."),
            field("ccsb_predecessoritemid", "Predecessor Snapshot Item", "Lookup", "No", "Self-reference.", "Prior snapshot item for same logical record."),
            field("ccsb_retentionuntil", "Retention Until", "Date and Time", "No", "User local; stored UTC.", "Earliest archive/purge eligibility."),
            field("ccsb_isimmutable", "Immutable", "Boolean", "Yes", "Default Yes.", "Server-side update/delete guard."),
        ],
        "relationships": [
            rel("ccsb_publishsnapshot_ccsb_publishsnapshotitem", "ccsb_publishsnapshotid", "ccsb_publishsnapshot", "Runtime required", "Snapshot header has many immutable items."),
            rel("ccsb_board_ccsb_publishsnapshotitem", "ccsb_boardid", "ccsb_board", "Optional", "Board support filtering."),
            rel("ccsb_boardversion_ccsb_publishsnapshotitem", "ccsb_boardversionid", "ccsb_boardversion", "Optional", "Configuration version context."),
            rel("ccsb_scheduleversion_ccsb_publishsnapshotitem", "ccsb_scheduleversionid", "ccsb_scheduleversion", "Optional", "Schedule version context."),
            rel("ccsb_operation_ccsb_publishsnapshotitem", "ccsb_operationid", "ccsb_operation", "Optional", "Publish/rollback operation."),
            rel("ccsb_operationitem_ccsb_publishsnapshotitem", "ccsb_operationitemid", "ccsb_operationitem", "Optional", "Operation item linkage."),
            rel("ccsb_schedulechange_ccsb_publishsnapshotitem", "ccsb_schedulechangeid", "ccsb_schedulechange", "Optional", "Change captured by snapshot item."),
            rel("ccsb_scheduleitem_ccsb_publishsnapshotitem", "ccsb_scheduleitemid", "ccsb_scheduleitem", "Optional", "Native schedule item linkage."),
            rel("ccsb_scheduleassignment_ccsb_publishsnapshotitem", "ccsb_scheduleassignmentid", "ccsb_scheduleassignment", "Optional", "Native assignment linkage."),
            rel("ccsb_schedulerequirement_ccsb_publishsnapshotitem", "ccsb_schedulerequirementid", "ccsb_schedulerequirement", "Optional", "Native requirement linkage."),
            rel("ccsb_resource_ccsb_publishsnapshotitem", "ccsb_resourceid", "ccsb_resource", "Optional", "Resource linkage."),
            rel("ccsb_publishsnapshotitem_ccsb_publishsnapshotitem_predecessor", "ccsb_predecessoritemid", "ccsb_publishsnapshotitem", "Optional", "Self-reference for version lineage."),
        ],
    },
    {
        "logical": "ccsb_publishlock",
        "display": "Publish Lock",
        "plural": "Publish Locks",
        "ownership": "UserOwned",
        "audit": "Enable audit; update allowed only through lock/unlock/override APIs.",
        "solution": "CCSB Foundation Schema v1.1 proposed",
        "purpose": "Protected scope that blocks or governs edits against official/published schedule state.",
        "alignment": "No direct URS table equivalent. This is CCSB's product-owned concurrency and release-governance lock, similar in spirit to approval/booking-status protection but explicit and queryable.",
        "alternate_keys": ["ccsb_PublishLock_Key: ccsb_lockkey"],
        "fields": [
            field("ccsb_publishlockid", "Publish Lock", "Uniqueidentifier", "System", "Primary ID; generated by Dataverse.", "Unique row identifier."),
            field("ccsb_name", "Publish Lock Name", "Primary Name", "Yes", "Max 300.", "Readable lock label."),
            field("ccsb_lockkey", "Lock Key", "Text", "Yes", "Max 200; alternate key.", "Stable lock identity."),
            field("ccsb_boardid", "Board", "Lookup", "Runtime required", "Target ccsb_board; metadata optional.", "Board protected by the lock."),
            field("ccsb_boardversionid", "Board Version", "Lookup", "No", "Target ccsb_boardversion.", "Configuration context."),
            field("ccsb_scheduleversionid", "Schedule Version", "Lookup", "No", "Target ccsb_scheduleversion.", "Schedule version protected."),
            field("ccsb_publishsnapshotid", "Publish Snapshot", "Lookup", "No", "Target ccsb_publishsnapshot.", "Snapshot that created or owns the lock."),
            field("ccsb_operationid", "Operation", "Lookup", "No", "Target ccsb_operation.", "Operation that created/updated the lock."),
            field("ccsb_operationitemid", "Operation Item", "Lookup", "No", "Target ccsb_operationitem.", "Operation item linkage."),
            field("ccsb_groupnodeid", "Group Node", "Lookup", "No", "Target ccsb_groupnode.", "Group/hierarchy scope."),
            field("ccsb_resourceid", "Resource", "Lookup", "No", "Target ccsb_resource.", "Resource scope."),
            field("ccsb_scheduleitemid", "Schedule Item", "Lookup", "No", "Target ccsb_scheduleitem.", "Schedule item scope."),
            field("ccsb_scheduleassignmentid", "Schedule Assignment", "Lookup", "No", "Target ccsb_scheduleassignment.", "Assignment scope."),
            field("ccsb_lockstatus", "Lock Status", "Choice", "Yes", "Pending, Active, Expired, Released, Superseded, Overridden.", "Current lock lifecycle state."),
            field("ccsb_locklevel", "Lock Level", "Choice", "Yes", "Informational, Soft Warning, Hard Block, Override Required, Read Only.", "How strongly the lock restricts operations."),
            field("ccsb_locktype", "Lock Type", "Choice", "Yes", "Publish Protection, Rollback Protection, Maintenance Window, Approval Hold, External Hold, System Recovery.", "Business purpose of lock."),
            field("ccsb_scopetype", "Scope Type", "Choice", "Yes", "Board, Schedule Version, Date Range, Group, Resource, Schedule Item, Assignment, Custom Query.", "Protected scope category."),
            field("ccsb_scopefrom", "Scope From", "Date and Time", "No", "User local; stored UTC.", "Start of date/time scope."),
            field("ccsb_scopeto", "Scope To", "Date and Time", "No", "User local; stored UTC.", "End of date/time scope."),
            field("ccsb_timezoneid", "Time Zone ID", "Text", "No", "Max 100.", "IANA/Windows time zone used to interpret scope."),
            field("ccsb_scopecriteriajson", "Scope Criteria JSON", "Multiline Text", "No", "Max 100000.", "Additional normalized scope filters."),
            field("ccsb_protectedactionsjson", "Protected Actions JSON", "Multiline Text", "No", "Max 100000.", "Actions blocked or requiring override, such as move, resize, assign, publish, rollback."),
            field("ccsb_lockownerid", "Lock Owner", "Lookup", "No", "Target systemuser.", "User responsible for the lock; Dataverse owner remains security owner."),
            field("ccsb_lockedby", "Locked By", "Lookup", "No", "Target systemuser.", "User/system that created the lock."),
            field("ccsb_lockedon", "Locked On", "Date and Time", "Yes", "User local; stored UTC.", "Lock activation timestamp."),
            field("ccsb_expireson", "Expires On", "Date and Time", "No", "User local; stored UTC.", "Automatic expiry timestamp."),
            field("ccsb_releasedby", "Released By", "Lookup", "No", "Target systemuser.", "User/system that released the lock."),
            field("ccsb_releasedon", "Released On", "Date and Time", "No", "User local; stored UTC.", "Release timestamp."),
            field("ccsb_overriddenby", "Overridden By", "Lookup", "No", "Target systemuser.", "User/system that overrode the lock."),
            field("ccsb_overriddenon", "Overridden On", "Date and Time", "No", "User local; stored UTC.", "Override timestamp."),
            field("ccsb_overridereason", "Override Reason", "Multiline Text", "No", "Max 4000; field security recommended.", "Required explanation for override.", "Field Security"),
            field("ccsb_supersedeslockid", "Supersedes Lock", "Lookup", "No", "Self-reference.", "Prior lock superseded by this lock."),
            field("ccsb_correlationid", "Correlation ID", "Text", "Yes", "Max 100.", "Trace correlation."),
            field("ccsb_retentionuntil", "Retention Until", "Date and Time", "No", "User local; stored UTC.", "Earliest archive/purge eligibility."),
            field("ccsb_isactive", "Active", "Boolean", "Yes", "Default Yes.", "Fast filter for active locks."),
        ],
        "relationships": [
            rel("ccsb_board_ccsb_publishlock", "ccsb_boardid", "ccsb_board", "Runtime required", "Board has many locks."),
            rel("ccsb_boardversion_ccsb_publishlock", "ccsb_boardversionid", "ccsb_boardversion", "Optional", "Configuration version context."),
            rel("ccsb_scheduleversion_ccsb_publishlock", "ccsb_scheduleversionid", "ccsb_scheduleversion", "Optional", "Schedule version lock."),
            rel("ccsb_publishsnapshot_ccsb_publishlock", "ccsb_publishsnapshotid", "ccsb_publishsnapshot", "Optional", "Snapshot that produced lock."),
            rel("ccsb_operation_ccsb_publishlock", "ccsb_operationid", "ccsb_operation", "Optional", "Operation that created/changed lock."),
            rel("ccsb_operationitem_ccsb_publishlock", "ccsb_operationitemid", "ccsb_operationitem", "Optional", "Operation item linkage."),
            rel("ccsb_groupnode_ccsb_publishlock", "ccsb_groupnodeid", "ccsb_groupnode", "Optional", "Group-level lock."),
            rel("ccsb_resource_ccsb_publishlock", "ccsb_resourceid", "ccsb_resource", "Optional", "Resource-level lock."),
            rel("ccsb_scheduleitem_ccsb_publishlock", "ccsb_scheduleitemid", "ccsb_scheduleitem", "Optional", "Schedule item lock."),
            rel("ccsb_scheduleassignment_ccsb_publishlock", "ccsb_scheduleassignmentid", "ccsb_scheduleassignment", "Optional", "Assignment lock."),
            rel("ccsb_publishlock_ccsb_publishlock_supersedes", "ccsb_supersedeslockid", "ccsb_publishlock", "Optional", "Lock lineage."),
            rel("systemuser_ccsb_publishlock_lockowner", "ccsb_lockownerid", "systemuser", "Optional", "Business owner of lock."),
            rel("systemuser_ccsb_publishlock_lockedby", "ccsb_lockedby", "systemuser", "Optional", "Creator of lock."),
            rel("systemuser_ccsb_publishlock_releasedby", "ccsb_releasedby", "systemuser", "Optional", "Release actor."),
            rel("systemuser_ccsb_publishlock_overriddenby", "ccsb_overriddenby", "systemuser", "Optional", "Override actor."),
        ],
    },
    {
        "logical": "ccsb_outboxevent",
        "display": "Outbox Event",
        "plural": "Outbox Events",
        "ownership": "OrganizationOwned",
        "audit": "Enable audit for status and error fields; payload fields field-secured.",
        "solution": "CCSB Foundation Schema v1.1 proposed",
        "purpose": "Durable transactional outbox event reserved for integration, connector, export, notification, and downstream delivery after CCSB state commits.",
        "alignment": "Generic Dataverse/enterprise outbox pattern. V1 should persist events but keep delivery disabled unless a governed connector capability is activated.",
        "alternate_keys": ["ccsb_OutboxEvent_Key: ccsb_eventkey"],
        "fields": [
            field("ccsb_outboxeventid", "Outbox Event", "Uniqueidentifier", "System", "Primary ID; generated by Dataverse.", "Unique row identifier."),
            field("ccsb_name", "Outbox Event Name", "Primary Name", "Yes", "Max 300.", "Readable event label."),
            field("ccsb_eventkey", "Event Key", "Text", "Yes", "Max 200; alternate key.", "Stable event identity."),
            field("ccsb_eventtype", "Event Type", "Choice", "Yes", "Schedule Changed, Publish Completed, Rollback Completed, Conflict Raised, Lock Changed, Projection Generated, Audit Event, Integration Test.", "Business event category."),
            field("ccsb_eventversion", "Event Version", "Text", "Yes", "Max 50; semantic version.", "Payload contract version."),
            field("ccsb_eventstatus", "Event Status", "Choice", "Yes", "Pending, Ready, Dispatching, Delivered, Failed, Dead Lettered, Cancelled, Suppressed.", "Delivery lifecycle status."),
            field("ccsb_boardid", "Board", "Lookup", "No", "Target ccsb_board.", "Board scope."),
            field("ccsb_boardversionid", "Board Version", "Lookup", "No", "Target ccsb_boardversion.", "Configuration version scope."),
            field("ccsb_scheduleversionid", "Schedule Version", "Lookup", "No", "Target ccsb_scheduleversion.", "Schedule version scope."),
            field("ccsb_operationid", "Operation", "Lookup", "Runtime required", "Target ccsb_operation; metadata optional.", "Operation that created event."),
            field("ccsb_operationitemid", "Operation Item", "Lookup", "No", "Target ccsb_operationitem.", "Operation item linkage."),
            field("ccsb_operationauditid", "Operation Audit", "Lookup", "No", "Target ccsb_operationaudit.", "Audit event that triggered outbox record."),
            field("ccsb_schedulechangeid", "Schedule Change", "Lookup", "No", "Target ccsb_schedulechange.", "Change event source."),
            field("ccsb_publishsnapshotid", "Publish Snapshot", "Lookup", "No", "Target ccsb_publishsnapshot.", "Publish event source."),
            field("ccsb_publishsnapshotitemid", "Publish Snapshot Item", "Lookup", "No", "Target ccsb_publishsnapshotitem.", "Snapshot item event source."),
            field("ccsb_publishlockid", "Publish Lock", "Lookup", "No", "Target ccsb_publishlock.", "Lock event source."),
            field("ccsb_correlationid", "Correlation ID", "Text", "Yes", "Max 100.", "End-to-end trace correlation."),
            field("ccsb_causationid", "Causation ID", "Text", "No", "Max 100.", "Event/request that caused this event."),
            field("ccsb_idempotencykey", "Idempotency Key", "Text", "No", "Max 200.", "Duplicate delivery prevention key."),
            field("ccsb_destinationtype", "Destination Type", "Choice", "Yes", "Disabled, Power Automate, Webhook, Service Bus, Event Grid, Dataverse, File Export, Other.", "Delivery channel type."),
            field("ccsb_destinationkey", "Destination Key", "Text", "No", "Max 200.", "Configured destination identifier; no secrets."),
            field("ccsb_topic", "Topic", "Text", "No", "Max 200.", "Routing topic or event subject."),
            field("ccsb_payloadcontenttype", "Payload Content Type", "Text", "Yes", "Max 100; default application/json.", "Payload media type."),
            field("ccsb_payloadjson", "Payload JSON", "Multiline Text", "No", "Max 100000; field security recommended.", "Minimized event payload; no secrets.", "Field Security"),
            field("ccsb_payloadhash", "Payload Hash", "Text", "No", "Max 128.", "Hash of normalized payload."),
            field("ccsb_payloadsizebytes", "Payload Size Bytes", "Whole Number", "No", "Non-negative.", "Payload size for limits and diagnostics."),
            field("ccsb_occurredon", "Occurred On", "Date and Time", "Yes", "User local; stored UTC.", "Business event timestamp."),
            field("ccsb_availableon", "Available On", "Date and Time", "No", "User local; stored UTC.", "Earliest dispatch timestamp."),
            field("ccsb_lockeduntil", "Locked Until", "Date and Time", "No", "User local; stored UTC.", "Worker lease expiry."),
            field("ccsb_locktoken", "Lock Token", "Text", "No", "Max 100.", "Worker lease token."),
            field("ccsb_attemptcount", "Attempt Count", "Whole Number", "Yes", "Default 0.", "Delivery attempt count."),
            field("ccsb_maxattempts", "Max Attempts", "Whole Number", "Yes", "Default 5.", "Delivery retry limit."),
            field("ccsb_retryafter", "Retry After", "Date and Time", "No", "User local; stored UTC.", "Next retry time."),
            field("ccsb_lastattempton", "Last Attempt On", "Date and Time", "No", "User local; stored UTC.", "Last dispatch attempt timestamp."),
            field("ccsb_deliveredon", "Delivered On", "Date and Time", "No", "User local; stored UTC.", "Delivery completion timestamp."),
            field("ccsb_errorcode", "Error Code", "Text", "No", "Max 100.", "Last delivery error code."),
            field("ccsb_errordetail", "Error Detail", "Multiline Text", "No", "Max 100000; field security recommended.", "Last delivery error details.", "Field Security"),
            field("ccsb_deadletterreason", "Dead Letter Reason", "Multiline Text", "No", "Max 4000.", "Reason event was dead-lettered."),
            field("ccsb_retentionuntil", "Retention Until", "Date and Time", "No", "User local; stored UTC.", "Earliest archive/purge eligibility."),
            field("ccsb_isreplayable", "Replayable", "Boolean", "Yes", "Default No.", "Whether support can safely replay event."),
        ],
        "relationships": [
            rel("ccsb_board_ccsb_outboxevent", "ccsb_boardid", "ccsb_board", "Optional", "Board scope."),
            rel("ccsb_boardversion_ccsb_outboxevent", "ccsb_boardversionid", "ccsb_boardversion", "Optional", "Configuration version scope."),
            rel("ccsb_scheduleversion_ccsb_outboxevent", "ccsb_scheduleversionid", "ccsb_scheduleversion", "Optional", "Schedule version scope."),
            rel("ccsb_operation_ccsb_outboxevent", "ccsb_operationid", "ccsb_operation", "Runtime required", "Operation created outbox event."),
            rel("ccsb_operationitem_ccsb_outboxevent", "ccsb_operationitemid", "ccsb_operationitem", "Optional", "Operation item linkage."),
            rel("ccsb_operationaudit_ccsb_outboxevent", "ccsb_operationauditid", "ccsb_operationaudit", "Optional", "Audit event source."),
            rel("ccsb_schedulechange_ccsb_outboxevent", "ccsb_schedulechangeid", "ccsb_schedulechange", "Optional", "Schedule change source."),
            rel("ccsb_publishsnapshot_ccsb_outboxevent", "ccsb_publishsnapshotid", "ccsb_publishsnapshot", "Optional", "Publish event source."),
            rel("ccsb_publishsnapshotitem_ccsb_outboxevent", "ccsb_publishsnapshotitemid", "ccsb_publishsnapshotitem", "Optional", "Snapshot item event source."),
            rel("ccsb_publishlock_ccsb_outboxevent", "ccsb_publishlockid", "ccsb_publishlock", "Optional", "Lock event source."),
        ],
    },
]


FIELD_VOCABULARY = [
    ("Identity", "ccsb_name", "Primary name on every CCSB table."),
    ("Identity", "ccsb_<entity>id", "Primary GUID generated by Dataverse."),
    ("Identity", "ccsb_<domain>key", "Stable text alternate key; sanitized for upsert."),
    ("Scope", "ccsb_boardid", "Stable CCSB board/configuration identity."),
    ("Scope", "ccsb_boardversionid", "Immutable configuration version."),
    ("Scope", "ccsb_scheduleversionid", "Operational schedule/release version."),
    ("Scope", "ccsb_scopetype / ccsb_scopecriteriajson", "Polymorphic protected/read scope."),
    ("Operation", "ccsb_operationid / ccsb_operationitemid", "Command execution and item evidence."),
    ("Operation", "ccsb_correlationid", "End-to-end support trace key."),
    ("Operation", "ccsb_idempotencykey", "Duplicate command/event prevention."),
    ("Source", "ccsb_sourceentitylogicalname", "Mapped/customer table logical name."),
    ("Source", "ccsb_sourcerecordid", "Mapped/customer record ID."),
    ("Source", "ccsb_sourcerowversion", "Concurrency token captured before write."),
    ("State", "ccsb_status / ccsb_*status / ccsb_*state", "Business lifecycle choices; do not replace Dataverse statecode/statuscode."),
    ("Time", "ccsb_effectivefrom / ccsb_effectiveto", "Validity window."),
    ("Time", "ccsb_occurredon / ccsb_requestedon / ccsb_committedon", "Operational timestamps stored UTC."),
    ("Evidence", "ccsb_*json", "Normalized payload/evidence JSON; secure when sensitive."),
    ("Evidence", "ccsb_*hash", "Hash of normalized payload/evidence."),
    ("Retention", "ccsb_retentionuntil", "Earliest archive/purge eligibility."),
]


CROSS_CHECKS = [
    ("Conflict naming", "Current model uses ccsb_conflict. Project docs sometimes say ccsb_conflictcase.", "Keep ccsb_conflict as canonical logical name; use 'Conflict Case' only as display text if desired."),
    ("Publish evidence", "ccsb_publishsnapshot exists as OrganizationOwned header with manifest JSON.", "Add ccsb_publishsnapshotitem as OrganizationOwned child rows; keep header logical name unchanged."),
    ("Audit/correlation", "ccsb_operation and ccsb_operationitem already carry correlation and payload fields.", "Add operationaudit/change/lock/outbox links to carry correlation through every support path."),
    ("Capabilities", "ccsb_resource has eligibilityattributesjson and ccsb_resourcerole has requiredskillcriteriajson, but no normalized capability records.", "Add ccsb_resourcecapability; backfill only from approved JSON/source mappings."),
    ("Rollback policy", "ccsb_fieldmapping has readenabled and writebehavior, but no independent rollback-managed or sensitive/display-only flags.", "Add field-level policy columns in a separate additive migration before enforcing field-scoped rollback."),
    ("Auditing", "Current dbmodel has entity-level audit disabled on custom tables.", "Enable table audit for the six new tables and reopen audit decision for existing control tables."),
]


VALIDATION_RULES = {
    "entityLogicalNameRegex": "^ccsb_[a-z][a-z0-9]*$",
    "fieldLogicalNameRegex": "^ccsb_[a-z][a-z0-9]*$",
    "relationshipSchemaRegex": "^(ccsb_[a-z0-9]+|systemuser)_(ccsb_[a-z0-9]+)(_[a-z0-9]+)?$",
    "requiredChecks": [
        "Every custom CCSB table logical name starts with ccsb_ and is lowercase.",
        "Every proposed table has primary id ccsb_<entity>id and primary name ccsb_name.",
        "Every custom field starts with ccsb_, except Dataverse system columns.",
        "Every lookup field ends with id and its target table exists in current or proposed metadata.",
        "Every new relationship uses Delete Restrict unless an explicit architecture decision approves otherwise.",
        "Alternate key fields are Text, Whole Number, Decimal, DateTime, Choice, or Lookup; are not field-secured; and stay below Dataverse key size limits.",
        "New fields on existing tables are optional at metadata level, then enforced by validation at activation/publish time.",
        "No existing logical name is renamed or dropped in a minor release.",
        "Payload, image, diagnostic, reason, and actor display fields are either minimized or field-secured.",
        "Evidence/control tables have table audit enabled and are protected by server-side append-only/update rules.",
    ],
    "backwardCompatibilityRules": [
        "Additive tables and optional columns are minor-version compatible.",
        "Changing type, logical name, ownership, or key composition is major-version breaking.",
        "Changing choice integer values is breaking; adding new choice values is minor-version compatible when consumers tolerate unknown values.",
        "Tightening a required field at metadata level is breaking for existing environments; enforce requiredness through activation validation first.",
    ],
}


MIGRATION_IMPACTS = [
    ("Add six missing tables", "Additive", "No existing rows invalidated. Import must create tables, relationships, keys, forms/views, security roles, and audit settings."),
    ("Normalize resource capabilities", "Data transform", "Backfill ccsb_resourcecapability from ccsb_resource.ccsb_eligibilityattributesjson, ccsb_resourcerole.ccsb_requiredskillcriteriajson, or Field Service bookable resource characteristics where mapped."),
    ("Split publish snapshot item evidence", "Data transform", "For existing snapshots, either leave legacy manifest-only snapshots as read-only or create snapshot item rows from manifestjson when enough record-level data exists."),
    ("Introduce schedule change ledger", "Behavioral", "New write path must create schedulechange before commit/publish. Existing schedule records can start with a baseline migration marker rather than synthetic history."),
    ("Add publish locks", "Behavioral", "Publish and rollback APIs must check locks. Existing published versions need initial active locks only if they should block edits after upgrade."),
    ("Add operation audit", "Behavioral/security", "Custom APIs and plug-ins must write operationaudit in the same transaction where possible and redact protected fields."),
    ("Add outbox event reservation", "Integration", "No connector should dispatch in V1 unless explicitly enabled. Existing integrations must not read raw schedule changes directly once outbox is active."),
    ("Add field mapping policy flags", "Schema dependency", "Recommended additive fields: ccsb_isrollbackmanaged, ccsb_issensitive, ccsb_isdisplayonly. These are required before field-scoped rollback is enforceable."),
    ("Audit enablement", "Governance", "Turning on audit affects storage and retention. Enable at environment, table, and column levels for control/evidence tables."),
    ("Security roles and field security", "Security", "Add privileges for support/publish/admin roles; field-security profiles for JSON payloads, reason text, actor display, and diagnostic details."),
    ("PCF/API contracts", "Dependency", "Read models and Custom APIs must include schedulechange, publishlock, snapshotitem, and correlation references."),
    ("Backward compatibility", "Versioning", "Ship as CCSB schema minor version. Do not rename existing ccsb_conflict, ccsb_publishsnapshot, ccsb_operation, or schedule graph fields."),
]


UPGRADE_PATH = [
    "v1.1 Additive schema: create the six tables, relationships, alternate keys, field security profiles, and audit settings. Keep all new lookups optional at metadata level.",
    "v1.1 Backfill mode: create resource capabilities and optional snapshot items from trustworthy existing JSON/manifests only. Record all backfills as ccsb_operation plus ccsb_operationaudit.",
    "v1.1 Compatibility gate: validation warns when publish lock, snapshot item, schedule change, or rollback field flags are absent for active boards.",
    "v1.2 Enforcement: publish/rollback Custom APIs require schedulechange, publishlock, snapshotitem, and operationaudit evidence for new publishes.",
    "v2.0 Breaking boundary, only if needed: remove legacy manifest-only or JSON-only compatibility after customer environments pass migration evidence gates.",
]


def esc(value):
    return html.escape("" if value is None else str(value))


def parse_existing_entities():
    wb = openpyxl.load_workbook(DBMODEL, read_only=True, data_only=True)
    ws = wb["Entities list"]
    rows = []
    for row in ws.iter_rows(min_row=4, values_only=True):
        if row and row[4] and str(row[4]).startswith("ccsb_"):
            rows.append(
                {
                    "display": row[0],
                    "logical": str(row[4]).lower(),
                    "ownership": row[8],
                    "audit": row[7],
                    "description": row[2],
                }
            )
    return rows


def write_csv(path: Path, headers, rows):
    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(headers)
        writer.writerows(rows)


def table(headers, rows):
    h = "".join(f"<th>{esc(x)}</th>" for x in headers)
    body = []
    for row in rows:
        body.append("<tr>" + "".join(f"<td>{esc(x)}</td>" for x in row) + "</tr>")
    return f'<div class="table"><table><tr>{h}</tr>{"".join(body)}</table></div>'


def field_table(entity):
    return table(
        ["Logical name", "Display", "Type", "Required", "Constraints", "Purpose", "Security"],
        [[f["logical"], f["display"], f["type"], f["required"], f["constraints"], f["purpose"], f["security"]] for f in entity["fields"]],
    )


def relationship_table(entity):
    return table(
        ["Relationship", "Lookup", "Target", "Cardinality", "Required", "Cascade", "Purpose"],
        [[r["relationship"], r["lookup"], r["target"], r["cardinality"], r["required"], r["cascade"], r["purpose"]] for r in entity["relationships"]],
    )


def css():
    return """
:root{--ink:#17232d;--muted:#5b6b77;--canvas:#f4f7fa;--paper:#fff;--line:#d8e1e8;--nav:#102c3e;--blue:#176b98;--green:#237a52;--amber:#9b6512;--red:#af3d49;--bluebg:#eaf4fa;--greenbg:#ebf7f0;--amberbg:#fff6e6;--redbg:#fff0f2}
*{box-sizing:border-box}body{margin:0;background:var(--canvas);color:var(--ink);font:14px/1.55 "Segoe UI",Arial,sans-serif}
.layout{display:grid;grid-template-columns:300px minmax(0,1fr);min-height:100vh}.side{position:sticky;top:0;height:100vh;overflow:auto;background:var(--nav);color:#e9f4f8;padding:24px 18px}
.brand{padding-bottom:16px;margin-bottom:16px;border-bottom:1px solid #ffffff26}.brand b{display:block;font-size:18px}.brand span{display:block;color:#b7d0dd;font-size:12px;margin-top:5px}
.label{font-size:10px;letter-spacing:.12em;text-transform:uppercase;color:#91b7ca;margin:18px 8px 7px}.side a{display:block;color:#dcecf4;text-decoration:none;padding:8px 9px;border-radius:7px;font-size:13px}.side a:hover{background:#1d4b64}
.doc{max-width:1380px;margin:0 auto;padding:32px 42px 72px}.hero,.section{background:var(--paper);border:1px solid var(--line);border-radius:10px}.hero{border-left:8px solid var(--blue);padding:28px 30px;box-shadow:0 8px 26px #102c3e12}.section{padding:24px 26px;margin:18px 0}
h1{font-size:30px;line-height:1.16;margin:0 0 10px;color:#123c59}h2{font-size:22px;margin:0 0 12px;color:#123e5b}h3{font-size:17px;margin:20px 0 8px;color:#184e6d}p{margin:8px 0}.lead{font-size:16px;color:#354a5b;max-width:1040px}
.grid{display:grid;gap:12px}.four{grid-template-columns:repeat(4,minmax(0,1fr))}.two{grid-template-columns:repeat(2,minmax(0,1fr))}
.metric{border:1px solid var(--line);border-radius:9px;padding:14px;background:#fff}.num{font-size:28px;line-height:1;font-weight:800;color:var(--blue)}.metric .txt{font-size:11px;line-height:1.25;font-weight:800;text-transform:uppercase;letter-spacing:.05em;color:var(--muted);margin-top:6px}
.callout{border-left:5px solid var(--blue);background:var(--bluebg);padding:13px 15px;border-radius:0 8px 8px 0;margin:15px 0}.callout.red{border-color:var(--red);background:var(--redbg)}.callout.amber{border-color:var(--amber);background:var(--amberbg)}.callout.green{border-color:var(--green);background:var(--greenbg)}
.table{overflow:auto;border:1px solid var(--line);border-radius:9px;margin:12px 0}table{border-collapse:collapse;width:100%;min-width:980px;background:#fff}th,td{padding:8px 9px;text-align:left;vertical-align:top;border-right:1px solid var(--line);border-bottom:1px solid var(--line)}th{background:#edf5f9;color:#174b67;font-size:11px;text-transform:uppercase;letter-spacing:.03em}tr:last-child td{border-bottom:0}th:last-child,td:last-child{border-right:0}
.tag{display:inline-block;border-radius:999px;padding:3px 8px;font-weight:800;font-size:11px;white-space:nowrap;background:#eaf4fa;color:#176b98}code{font:12px Consolas,"Courier New",monospace;background:#eff4f7;border:1px solid #d4e0e8;border-radius:4px;padding:1px 4px}
ul,ol{margin:8px 0 8px 20px;padding:0}li{margin:5px 0}.small,.footer{font-size:12px;color:var(--muted)}
@media(max-width:960px){.layout{display:block}.side{position:static;height:auto}.side nav{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:2px}.doc{padding:22px 16px}.four,.two{grid-template-columns:1fr}}
"""


def render_html(existing):
    nav_links = [
        ("summary", "Summary"),
        ("principles", "Design Principles"),
        ("entities", "Proposed Schemas"),
        ("inventory", "Canonical Inventory"),
        ("validation", "Logical-Name Tests"),
        ("migration", "Migration Impact"),
        ("decisions", "Design Notes"),
        ("sources", "Sources"),
    ]
    nav = "".join(f'<a href="#{anchor}">{label}</a>' for anchor, label in nav_links)
    existing_rows = [[e["logical"], e["display"], e["ownership"], e["audit"], e["description"]] for e in existing]
    proposed_rows = [[e["logical"], e["display"], e["ownership"], e["audit"], e["alignment"]] for e in ENTITIES]
    field_vocab_rows = [[a, b, c] for a, b, c in FIELD_VOCABULARY]
    cross_rows = [[a, b, c] for a, b, c in CROSS_CHECKS]
    migration_rows = [[a, b, c] for a, b, c in MIGRATION_IMPACTS]
    source_rows = [[s["label"], s["url"], s["use"]] for s in SOURCES]

    entity_sections = []
    for e in ENTITIES:
        entity_sections.append(
            f"""
<h3>{esc(e['display'])} <code>{esc(e['logical'])}</code></h3>
<p>{esc(e['purpose'])}</p>
<p><strong>Ownership:</strong> {esc(e['ownership'])}. <strong>Audit:</strong> {esc(e['audit'])}</p>
<p><strong>Dynamics alignment:</strong> {esc(e['alignment'])}</p>
<p><strong>Alternate keys:</strong> {', '.join(f'<code>{esc(k)}</code>' for k in e['alternate_keys'])}</p>
{field_table(e)}
{relationship_table(e)}
"""
        )

    validation_items = "".join(f"<li>{esc(x)}</li>" for x in VALIDATION_RULES["requiredChecks"])
    backward_items = "".join(f"<li>{esc(x)}</li>" for x in VALIDATION_RULES["backwardCompatibilityRules"])
    upgrade_items = "".join(f"<li>{esc(x)}</li>" for x in UPGRADE_PATH)

    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>CCSB Entity Design and Canonical Inventory Validation</title>
<style>{css()}</style>
</head>
<body>
<div class="layout">
<aside class="side"><div class="brand"><b>CCSB Entity Design</b><span>Missing Dataverse schema and validation plan<br>Prepared 2026-07-04</span></div><nav><div class="label">Navigation</div>{nav}</nav></aside>
<main class="doc">
<section id="summary" class="hero">
<div class="small" style="text-transform:uppercase;letter-spacing:.1em;font-weight:800;color:#176b98">Schema hardening deliverable</div>
<h1>CCSB Entity Design and Canonical Inventory Validation</h1>
<p class="lead">This report defines the six missing Dataverse tables needed to close the V1 control, publish, audit, lock, capability, and outbound reliability gaps: <code>ccsb_resourcecapability</code>, <code>ccsb_operationaudit</code>, <code>ccsb_schedulechange</code>, <code>ccsb_publishsnapshotitem</code>, <code>ccsb_publishlock</code>, and <code>ccsb_outboxevent</code>.</p>
<div class="grid four" style="margin-top:16px">
<div class="metric"><div class="num">{len(existing)}</div><div class="txt">Existing ccsb tables read from dbmodel</div></div>
<div class="metric"><div class="num">{len(ENTITIES)}</div><div class="txt">Proposed new tables</div></div>
<div class="metric"><div class="num">{sum(len(e['fields']) for e in ENTITIES)}</div><div class="txt">Proposed fields</div></div>
<div class="metric"><div class="num">{sum(len(e['relationships']) for e in ENTITIES)}</div><div class="txt">Proposed relationships</div></div>
</div>
<div class="callout amber"><strong>Design stance:</strong> add these as an additive schema baseline, keep all delete behavior Restrict, make existing-table lookups metadata-optional for upgrade safety, and enforce business-required links in validation and Custom APIs.</div>
</section>

<section id="principles" class="section">
<h2>1. Design Principles</h2>
<ul>
<li>Keep canonical logical names stable: no renames of existing CCSB tables or fields in a minor release.</li>
<li>Use explicit tables for audit, lock, change, snapshot item, outbox, and capability records instead of burying V1 control behavior in large JSON fields.</li>
<li>Use <code>Restrict</code> delete on all relationships so evidence cannot disappear through parent deletion.</li>
<li>Use user-owned tables where board/business-unit scoped security matters; use organization-owned tables for immutable publish evidence and system queue records.</li>
<li>Use Dataverse auditing for platform-level history and <code>ccsb_operationaudit</code> for product-level reason, policy, correlation, and field-scope evidence.</li>
<li>Reserve outbound integration through <code>ccsb_outboxevent</code>; do not enable connector dispatch until an explicit integration capability is approved.</li>
</ul>
</section>

<section id="entities" class="section">
<h2>2. Proposed Entity Schemas</h2>
{''.join(entity_sections)}
</section>

<section id="inventory" class="section">
<h2>3. Canonical Entity and Field Inventory</h2>
<h3>Proposed canonical tables</h3>
{table(["Logical name", "Display name", "Ownership", "Audit posture", "D365/Dataverse alignment"], proposed_rows)}
<h3>Existing CCSB tables from dbmodel.xlsx</h3>
{table(["Logical name", "Display name", "Ownership", "Entity audit enabled", "Description"], existing_rows)}
<h3>Canonical field vocabulary</h3>
{table(["Group", "Canonical field pattern", "Usage"], field_vocab_rows)}
<h3>Cross-solution consistency checks</h3>
{table(["Check", "Current observation", "Recommendation"], cross_rows)}
</section>

<section id="validation" class="section">
<h2>4. Logical-Name Validation Test Plan</h2>
<div class="callout green"><strong>Automate this in CI:</strong> run the validation against <code>dbmodel.xlsx</code>, provisioner schema JSON, unpacked solution XML, and live Dataverse metadata inventory before every schema PR and before every managed solution export.</div>
<p><strong>Entity regex:</strong> <code>{esc(VALIDATION_RULES['entityLogicalNameRegex'])}</code></p>
<p><strong>Field regex:</strong> <code>{esc(VALIDATION_RULES['fieldLogicalNameRegex'])}</code></p>
<p><strong>Relationship regex:</strong> <code>{esc(VALIDATION_RULES['relationshipSchemaRegex'])}</code></p>
<h3>Required automated checks</h3>
<ol>{validation_items}</ol>
<h3>Backward compatibility checks</h3>
<ol>{backward_items}</ol>
</section>

<section id="migration" class="section">
<h2>5. Migration-Impact Assessment</h2>
{table(["Impact", "Type", "Action"], migration_rows)}
<h3>Upgrade path recommendation</h3>
<ol>{upgrade_items}</ol>
</section>

<section id="decisions" class="section">
<h2>6. Design Decisions and Alignment Notes</h2>
<div class="grid two">
<div class="callout">
<strong>Field Service and URS alignment</strong>
<p>Resource capabilities mirror bookable resource characteristics, categories, territories, proficiency/rating, resource type, work-hour availability, and enable-for-availability concepts without requiring CCSB to depend on Field Service tables.</p>
</div>
<div class="callout">
<strong>Project Operations alignment</strong>
<p>Roles, requirements, and capabilities stay generic enough to model project/resource skills and roles, while CCSB remains server-authoritative through Custom APIs rather than direct client mutation.</p>
</div>
<div class="callout">
<strong>Generic Dataverse alignment</strong>
<p>Alternate keys use supported non-secured columns; all relationship deletes are Restrict; payload/reason/error fields use field security; auditing is enabled at environment/table/column levels.</p>
</div>
<div class="callout">
<strong>Publish and rollback alignment</strong>
<p>Snapshot item and schedule change records provide field-scoped rollback evidence. Publish locks prevent official-state mutation without approved override and audit evidence.</p>
</div>
</div>
</section>

<section id="sources" class="section">
<h2>7. Sources</h2>
{table(["Source", "URL", "Used for"], source_rows)}
<p class="footer">Generated from the current CCSB workspace and <code>metadata/dbmodel.xlsx</code>. Output CSVs are in the same deliverable folder.</p>
</section>
</main></div></body></html>
"""


def main():
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    existing = parse_existing_entities()

    field_rows = []
    rel_rows = []
    entity_rows = []
    for entity in ENTITIES:
        entity_rows.append(
            [
                entity["logical"],
                entity["display"],
                entity["plural"],
                entity["ownership"],
                entity["audit"],
                entity["solution"],
                entity["purpose"],
                entity["alignment"],
                "; ".join(entity["alternate_keys"]),
            ]
        )
        for f in entity["fields"]:
            field_rows.append(
                [
                    entity["logical"],
                    entity["display"],
                    f["logical"],
                    f["display"],
                    f["type"],
                    f["required"],
                    f["constraints"],
                    f["purpose"],
                    f["security"],
                ]
            )
        for r in entity["relationships"]:
            rel_rows.append(
                [
                    entity["logical"],
                    r["relationship"],
                    r["lookup"],
                    r["target"],
                    r["cardinality"],
                    r["required"],
                    r["cascade"],
                    r["purpose"],
                ]
            )

    write_csv(
        OUT_DIR / "ccsb-proposed-entity-inventory.csv",
        ["LogicalName", "DisplayName", "PluralName", "Ownership", "Audit", "Solution", "Purpose", "DynamicsAlignment", "AlternateKeys"],
        entity_rows,
    )
    write_csv(
        OUT_DIR / "ccsb-proposed-field-inventory.csv",
        ["EntityLogicalName", "EntityDisplayName", "FieldLogicalName", "FieldDisplayName", "Type", "Required", "Constraints", "Purpose", "Security"],
        field_rows,
    )
    write_csv(
        OUT_DIR / "ccsb-proposed-relationship-inventory.csv",
        ["EntityLogicalName", "RelationshipName", "LookupField", "TargetTable", "Cardinality", "Required", "Cascade", "Purpose"],
        rel_rows,
    )
    (OUT_DIR / "ccsb-logical-name-validation-rules.json").write_text(json.dumps(VALIDATION_RULES, indent=2), encoding="utf-8")
    (OUT_DIR / "ccsb-entity-design-canonical-inventory-validation.html").write_text(render_html(existing), encoding="utf-8")

    print(
        json.dumps(
            {
                "html": str(OUT_DIR / "ccsb-entity-design-canonical-inventory-validation.html"),
                "entity_csv": str(OUT_DIR / "ccsb-proposed-entity-inventory.csv"),
                "field_csv": str(OUT_DIR / "ccsb-proposed-field-inventory.csv"),
                "relationship_csv": str(OUT_DIR / "ccsb-proposed-relationship-inventory.csv"),
                "validation_json": str(OUT_DIR / "ccsb-logical-name-validation-rules.json"),
                "proposed_entities": len(ENTITIES),
                "proposed_fields": len(field_rows),
                "proposed_relationships": len(rel_rows),
            },
            indent=2,
        )
    )


if __name__ == "__main__":
    main()

